# https://github.com/calogica/dbt-expectations

version: 2

models:
    - name: dim_listing_cleansed
      description: cleansed listing table
      columns:
        - name: listing_id
          description: Primary key for listing table
          tests:
            - unique
            - not_null

        - name: host_id
          description: references to primary key of hosts table
          tests:
            - not_null
            - relationships:
                field: host_id
                to: ref('dim_host_cleansed')
        
        - name: room_type
          description: type of room
          tests:
            - accepted_values:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

    - name: dim_hosts_cleansed
      description: cleansed host table

    - name: dim_listing_w_hosts
      tests:
        - dbt_expectations.expect_table_row_count_to_equal_other_table:
            compare_model: ref("dim_listing_cleansed")
           
          # compare_model: source('airbnb', 'listings')
      columns:
        - name: price
          tests:
            - dbt_expectations.expect_column_values_to_match_regex:
                regex: "^\\\\$[0-9][0-9\\\\.]+$"

            - dbt_expectations.expect_column_quantile_values_to_be_between:
                quantile: 0.99
                min_value: 0 
                max_value: 500

            - dbt_expectations.expect_column_max_to_be_between:
                max_value: 500
                config:
                  severity: warn

               